version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soloq
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: soloq_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app


  frontend:
    build: ./frontend
    container_name: soloq_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
    command: npm run dev
volumes:
  db_data:
